

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #defaultZone : http://localhost:8761/eureka/
      defaultZone : https://zed-register-eureka-server-3e07ae708abe.herokuapp.com/eureka/

  server:
    eviction-interval-timer-in-ms: 5000

spring:
  application:
    name: gateway-routing
  cloud:
    gateway:
      routes:
#        - id: order-service
#          predicates:
#            - Path=/api/orders/**
#          uri: https://nexio-order-service.herokuapp.com/
  
#              
#        - id: stocks-service
#          predicates:
#            - Path=/api/stocks/**
#          uri: https://nexio-stock-service.herokuapp.com/
#

          
        - id: zed-order-service
          predicates:
            - Path=/api/orders/**
          #uri: http://localhost:9090/
          uri: https://zed-order-service-cd54f752cf9a.herokuapp.com/
                    
        - id: zed-stock-service
          predicates:
            - Path=/api/stocks/**
          #uri: http://localhost:9191/
          uri: https://zed-stock-service-71dbea08ba3d.herokuapp.com/  
                
        
            
            
